package net.aros.pways.client.openutil;

import net.aros.pways.Pways;
import net.fabricmc.loader.api.FabricLoader;
import net.minecraft.SharedConstants;
import net.minecraft.entity.player.PlayerEntity;
import net.minecraft.resource.ResourcePack;
import net.minecraft.util.Identifier;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;

class ResourceExtractor {
    private static final String TEMP_PACK_NAME = "resourcepacks/__repainted__";
    private static final String PACK_META_CONTENT = "{\"pack\": {\"pack_format\": %d, \"description\": \"Generated by PWAYS\"}}".formatted(SharedConstants.RESOURCE_PACK_VERSION);

    static @NotNull Path extractToTemporaryPack(PlayerEntity player, String modNamespace) {
        Path gameDir = FabricLoader.getInstance().getGameDir();
        Path tempPackDir = gameDir.resolve(TEMP_PACK_NAME);
        Path assetsDir = tempPackDir.resolve("assets");
        Path modAssetsDir = assetsDir.resolve(modNamespace);

        if (shouldSkipExtraction(modAssetsDir)) {
            return modAssetsDir;
        }

        createDirectoriesSafely(assetsDir);
        writePackMeta(tempPackDir.resolve(ResourcePack.PACK_METADATA_NAME));
        extractModAssets(player, modNamespace, assetsDir);
        return modAssetsDir;
    }

    private static boolean shouldSkipExtraction(Path modAssetsDir) {
        return Files.exists(modAssetsDir) && !Pways.CONFIG.alwaysRewrite();
    }

    private static void createDirectoriesSafely(Path directory) {
        try {
            Files.createDirectories(directory);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    private static void writePackMeta(Path metaPath) {
        try (BufferedWriter writer = Files.newBufferedWriter(metaPath)) {
            writer.write(PACK_META_CONTENT);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    private static void extractModAssets(PlayerEntity player, String modNamespace, Path assetsDir) {
        if (Identifier.DEFAULT_NAMESPACE.equals(modNamespace)) {
            Path vanillaZip = VanillaDownloader.downloadVanillaAssets(player);
            if (vanillaZip != null) {
                extractFromArchive(vanillaZip, assetsDir, true);
            }
        } else {
            Path modPath = FabricLoader.getInstance().getModContainer(modNamespace).orElseThrow().getOrigin().getPaths().getFirst();
            extractFromArchive(modPath, assetsDir, false);
        }
    }

    private static void extractFromArchive(Path archivePath, Path targetDir, boolean isVanilla) {
        try (ZipInputStream zipStream = new ZipInputStream(Files.newInputStream(archivePath))) {
            createDirectoriesSafely(targetDir);
            ZipEntry entry;
            while ((entry = zipStream.getNextEntry()) != null) {
                processZipEntry(entry, zipStream, targetDir, isVanilla);
                zipStream.closeEntry();
            }
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    private static void processZipEntry(ZipEntry entry, ZipInputStream zipStream, Path targetDir, boolean isVanilla) throws IOException {
        String relativePath = computeRelativePath(isVanilla, entry);
        if (relativePath != null && !relativePath.isEmpty()) {
            Path targetPath = targetDir.resolve(relativePath);
            if (entry.isDirectory()) {
                Files.createDirectories(targetPath);
            } else {
                createDirectoriesSafely(targetPath.getParent());
                Files.copy(zipStream, targetPath, StandardCopyOption.REPLACE_EXISTING);
            }
        }
    }

    private static String computeRelativePath(boolean isVanilla, @NotNull ZipEntry entry) {
        String entryName = entry.getName();
        if (isVanilla) {
            return extractVanillaRelativePath(entryName);
        } else {
            return extractModRelativePath(entryName);
        }
    }

    private static @Nullable String extractVanillaRelativePath(@NotNull String entryName) {
        if (entryName.startsWith("minecraft-assets") && entryName.contains("/assets/")) {
            int assetsIndex = entryName.indexOf("/assets/");
            if (assetsIndex != -1) {
                return entryName.substring(assetsIndex + "/assets/".length());
            }
        }
        return null;
    }

    private static @Nullable String extractModRelativePath(@NotNull String entryName) {
        if (entryName.startsWith("assets/")) {
            return entryName.substring("assets/".length());
        }
        return null;
    }
}