package net.aros.pways.client;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import net.aros.pways.Pways;
import net.fabricmc.loader.api.FabricLoader;
import net.minecraft.SharedConstants;
import net.minecraft.block.Block;
import net.minecraft.client.MinecraftClient;
import net.minecraft.entity.player.PlayerEntity;
import net.minecraft.item.Item;
import net.minecraft.registry.Registries;
import net.minecraft.resource.Resource;
import net.minecraft.text.Text;
import net.minecraft.util.Formatting;
import net.minecraft.util.Identifier;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.Unmodifiable;

import java.io.BufferedWriter;
import java.io.IOException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.List;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;

import static net.aros.pways.Pways.MOD_ID;

public class OpenUtil {
    @SuppressWarnings("deprecation")
    public static final String MCMETA = "{\"pack\": {\"pack_format\": %d, \"description\": \"Generated by PWAYS\"}}".formatted(SharedConstants.RESOURCE_PACK_VERSION);

    public static void openTextures(@NotNull Item item, @NotNull PlayerEntity player) {
        Identifier itemId = Registries.ITEM.getId(item);
        List<Identifier> textures = getSubModelsOfModel(itemId.withPrefixedPath("models/item/"))
                .stream()
                .map(OpenUtil::getTexturesOfModel)
                .flatMap(List::stream)
                .distinct()
                .map(id -> id.withSuffixedPath(".png"))
                .toList();
        openWithNewProcess(player, Pways.CONFIG.pathToAseprite(), textures);
    }

    public static void openTextures(@NotNull Block block, @NotNull PlayerEntity player) {
        Identifier blockId = Registries.BLOCK.getId(block);
        List<Identifier> textures = getBlockModels(blockId)
                .stream()
                .map(OpenUtil::getSubModelsOfModel)
                .flatMap(List::stream)
                .map(OpenUtil::getTexturesOfModel)
                .flatMap(List::stream)
                .distinct()
                .map(id -> id.withSuffixedPath(".png"))
                .toList();
        openWithNewProcess(player, Pways.CONFIG.pathToAseprite(), textures);
    }

    public static void openModels(@NotNull Item item, @NotNull PlayerEntity player) {
        Identifier itemId = Registries.ITEM.getId(item);
        openWithNewProcess(player, Pways.CONFIG.pathToBlockbench(), getSubModelsOfModel(itemId.withPrefixedPath("models/item/")).stream().map(id -> id.withSuffixedPath(".json")).toList());
    }

    public static void openModels(@NotNull Block block, @NotNull PlayerEntity player) {
        Identifier blockId = Registries.BLOCK.getId(block);
        openWithNewProcess(player, Pways.CONFIG.pathToBlockbench(), getBlockModels(blockId).stream().map(id -> id.withSuffixedPath(".json")).toList());
    }

    private static @NotNull List<Identifier> getTexturesOfModel(@NotNull Identifier id) {
        List<Identifier> foundTextures = new ArrayList<>();
        JsonObject object = getResourceAsParsedJson(id);
        if (!object.has("textures")) return List.of();
        JsonObject textures = object.getAsJsonObject("textures");
        for (String key : textures.keySet()) {
            foundTextures.add(Identifier.of(textures.getAsJsonPrimitive(key).getAsString()).withPrefixedPath("textures/"));
        }
        return foundTextures;
    }

    private static @NotNull @Unmodifiable List<Identifier> getSubModelsOfModel(@NotNull Identifier id) {
        List<Identifier> foundModels = new ArrayList<>();
        foundModels.add(id);
        JsonObject baseModel = getResourceAsParsedJson(id);
        if (baseModel.has("overrides")) {
            JsonArray overrides = baseModel.getAsJsonArray("overrides");
            for (JsonElement element : overrides) {
                foundModels.addAll(getSubModelsOfModel(Identifier.of(element.getAsJsonObject().getAsJsonPrimitive("model").getAsString()).withPrefixedPath("models/")));
            }
        }
        return foundModels.stream().distinct().toList();
    }

    private static @NotNull List<Identifier> getBlockModels(@NotNull Identifier id) {
        List<Identifier> models = new ArrayList<>();
        JsonObject object = getResourceAsParsedJson(id.withPrefixedPath("blockstates/"));
        JsonObject variants = object.getAsJsonObject("variants");
        for (String key : variants.keySet()) {
            List<JsonElement> sub = new ArrayList<>();
            if (variants.get(key).isJsonArray()) {
                sub.addAll(variants.getAsJsonArray(key).asList());
            } else if (variants.get(key).isJsonObject()) {
                sub.add(variants.getAsJsonObject(key));
            }

            models.addAll(sub.stream().map(e -> Identifier.of(e.getAsJsonObject().getAsJsonPrimitive("model").getAsString()).withPrefixedPath("models/")).distinct().toList());
        }
        return models;
    }

    private static JsonObject getResourceAsParsedJson(@NotNull Identifier id) {
        try {
            return JsonParser.parseReader(getResource(id.withSuffixedPath(".json")).getReader()).getAsJsonObject();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    private static Resource getResource(Identifier id) {
        return MinecraftClient.getInstance().getResourceManager().getAllResources(id).stream().findFirst().orElseThrow();
    }

    private static void openWithNewProcess(PlayerEntity player, String pathToProgram, @NotNull List<Identifier> modAndAssetPaths) {
        if (modAndAssetPaths.isEmpty()) {
            player.sendMessage(Text.translatable("msg." + MOD_ID + ".assets_not_found").formatted(Formatting.RED, Formatting.ITALIC));
            return;
        }
        if (pathToProgram.isBlank()) {
            player.sendMessage(Text.translatable("msg." + MOD_ID + ".program_is_empty").formatted(Formatting.RED, Formatting.ITALIC));
            return;
        }
        if (!Files.exists(Paths.get(pathToProgram))) {
            player.sendMessage(Text.translatable("msg." + MOD_ID + ".program_not_found").formatted(Formatting.RED, Formatting.ITALIC));
            return;
        }
        List<String> args = new ArrayList<>();
        args.add(pathToProgram);
        for (Identifier modAndAssetPath : modAndAssetPaths) {
            Path path = OpenUtil.extractToResourcePack(player, modAndAssetPath.getNamespace()).resolve(modAndAssetPath.getPath());
            args.add(path.toAbsolutePath().toString());
        }
        try {
            new ProcessBuilder(args).start();
        } catch (IOException e) {
            player.sendMessage(Text.translatable("msg." + MOD_ID + ".process_error").formatted(Formatting.RED, Formatting.ITALIC));
            Pways.LOGGER.info("Brush PROCESS error. Args: {}", args, e);
        }
    }

    private static @NotNull Path extractToResourcePack(PlayerEntity player, String mod) {
        Path to = FabricLoader.getInstance().getGameDir().resolve("resourcepacks/__repainted__");
        Path result = to.resolve("assets").resolve(mod);

        if (Files.exists(to.resolve("assets").resolve(mod)) && !Pways.CONFIG.alwaysRewrite()) {
            return result;
        }
        try {
            Files.createDirectories(to.resolve("assets"));
        } catch (IOException e) {
            throw new RuntimeException(e);
        }

        writeMcMeta(to.resolve("pack.mcmeta"));
        if (Identifier.DEFAULT_NAMESPACE.equals(mod)) {
            Path got = downloadVanilla(player);
            if (got != null) extractAssets(got, to.resolve("assets"), true);
            return result;
        }
        extractAssets(getJarPathTo(mod), to.resolve("assets"), false);
        return result;
    }

    private static @Nullable Path downloadVanilla(PlayerEntity player) {
        try (HttpClient client = HttpClient.newBuilder().followRedirects(HttpClient.Redirect.ALWAYS).build()) {
            URI zipUri = URI.create("https://github.com/InventivetalentDev/minecraft-assets/archive/refs/heads/1.21.1.zip");
            Path tempZip = Files.createTempFile("minecraft-assets", ".zip");

            HttpRequest request = HttpRequest
                    .newBuilder(zipUri)
                    .header("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36")
                    .build();
            HttpResponse<Path> response = client.send(request, HttpResponse.BodyHandlers.ofFile(tempZip));
            if (response.statusCode() != 200) {
                throw new IOException("Failed to download ZIP: HTTP " + response.statusCode());
            }

            return tempZip;
        } catch (Throwable t) {
            player.sendMessage(Text.translatable("msg." + MOD_ID + ".vanilla_download_fail").formatted(Formatting.RED, Formatting.ITALIC));
            Pways.LOGGER.error("Failed to download vanilla assets", t);
            return null;
        }
    }

    private static Path getJarPathTo(String mod) {
        return FabricLoader.getInstance().getModContainer(mod).orElseThrow().getOrigin().getPaths().getFirst();
    }

    private static void writeMcMeta(Path to) {
        try (BufferedWriter writer = Files.newBufferedWriter(to)) {
            writer.write(MCMETA);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    private static void extractAssets(Path archivePath, Path targetDir, boolean vanilla) {
        try (ZipInputStream zis = new ZipInputStream(Files.newInputStream(archivePath))) {
            Files.createDirectories(targetDir);

            ZipEntry entry;
            while ((entry = zis.getNextEntry()) != null) {
                String relativePath = getRelativePath(vanilla, entry);

                if (relativePath != null && !relativePath.isEmpty()) {
                    Path targetPath = targetDir.resolve(relativePath);

                    if (entry.isDirectory()) {
                        Files.createDirectories(targetPath);
                    } else {
                        Files.createDirectories(targetPath.getParent());
                        Files.copy(zis, targetPath, StandardCopyOption.REPLACE_EXISTING);
                    }
                }
                zis.closeEntry();
            }
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    private static @Nullable String getRelativePath(boolean vanilla, @NotNull ZipEntry entry) {
        String entryName = entry.getName();

        String relativePath;
        if (vanilla) {
            if (entryName.startsWith("minecraft-assets") && entryName.contains("/assets/")) {
                int assetsIndex = entryName.indexOf("/assets/");
                if (assetsIndex != -1) {
                    relativePath = entryName.substring(assetsIndex + "/assets/".length());
                } else {
                    relativePath = null;  // Не обрабатываем, если нет /assets/
                }
            } else {
                relativePath = null;  // Не обрабатываем другие entry
            }
        } else {
            if (entryName.startsWith("assets/")) {
                relativePath = entryName.substring("assets/".length());
            } else {
                relativePath = null;
            }
        }
        return relativePath;
    }
}
